import { MusicPiece } from './types';

const rawMusicData: MusicPiece[] = [
  {
    composer: 'Beethoven',
    title: 'Symphony No.5, I',
    youtubeId: 'jv2WJMVPQi8',
    week: 'Week 1-2',
    keyPoint: 'Fate knocking: short-short-short-long.',
    youtubeStartTime: 7,
  },
  {
    composer: 'Chopin',
    title: 'Tristesse Etude',
    youtubeId: 'efUpNxQPLMU',
    week: 'Week 1-2',
    keyPoint: "'Tristesse' = Sadness. Both fast and slow dynamics",
    youtubeStartTime: 23,
  },
  {
    composer: 'Puccini',
    title: 'O mio babbino caro (Oh My Dear Papa)',
    youtubeId: '0Wlcr2bIKmk',
    week: 'Week 1-2',
    keyPoint: "Soprano aria: 'Oh my dear papa'.",
    youtubeStartTime: 0,
  },
  {
    composer: 'di Capua',
    title: 'O Sole mio',
    youtubeId: '12I2TkWJimI',
    week: 'Week 1-2',
    keyPoint: "Famous tenor song: 'My Sunshine'.",
    youtubeStartTime: 0,
  },
  {
    composer: 'The Beatles',
    title: 'Honey Pie',
    youtubeId: 'bY9AqiAXCWM',
    week: 'Week 1-2',
    keyPoint: 'Vaudeville style, sounds like an old 1920s record.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Beethoven',
    title: 'Symphony No.9, IV (Choral Symphony)',
    youtubeId: 'oiwxEvCzHKw',
    week: 'Week 1-2',
    keyPoint: "Famous 'Ode to Joy' theme. EU anthem.",
    youtubeStartTime: 3380,
  },
  {
    composer: 'Mozart',
    title: 'Eine kleine nachtmusik, I',
    youtubeId: 'oy2zDJPIgwc',
    week: 'Week 1-2',
    keyPoint: "'A Little Night Music'. Cheerful & famous opening.",
    youtubeStartTime: 0,
  },
  {
    composer: 'Strauss I',
    title: 'Radetzky March',
    youtubeId: '8_2oDRiLYlc',
    week: 'Week 1-2',
    keyPoint: 'Lively march. Audience claps along.',
    youtubeStartTime: 146,
  },
  {
    composer: 'Vivaldi',
    title: 'Lute Concerto, I',
    youtubeId: '7hPNBjCSJLo',
    week: 'Week 1-2',
    keyPoint: 'Gentle, plucked sound of the lute (like a guitar).',
    youtubeStartTime: 25,
  },
  {
    composer: 'Beethoven',
    title: 'Symphony No.5, IV',
    youtubeId: 'DAyUzxDB9eE',
    week: 'Week 1-2',
    keyPoint: 'Triumphant finale: a journey from darkness to light.',
    youtubeStartTime: 25,
  },
  {
    composer: 'Pachelbel',
    title: 'Canon in D',
    youtubeId: 'NlprozGcs80',
    week: 'Week 3',
    keyPoint: 'Repeating bass line. Popular wedding music.',
    youtubeStartTime: 55,
  },
  {
    composer: 'Vivaldi',
    title: 'Four Seasons - Spring, I',
    youtubeId: 'l-dYNttdgl0',
    week: 'Week 3',
    keyPoint: 'Musically sounds like birds, streams, thunderstorms.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Vivaldi',
    title: 'Four Seasons - Winter, I',
    youtubeId: 'CLiznLYZPRI',
    week: 'Week 3',
    keyPoint: 'Musically sounds like chattering teeth & stamping feet.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Bach',
    title: 'Toccata and Fugue',
    youtubeId: 'Nnuq9PXbywA',
    week: 'Week 3',
    keyPoint: 'Dramatic organ music. Used in horror films & *Fantasia*.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Drayton',
    title: 'Masterpiece',
    youtubeId: '6bmRE-cTg_Q',
    week: 'Week 3',
    keyPoint: 'Acapella with "Johann Sebastian Bach" vocalises.',
    youtubeStartTime: 70,
  },
  {
    composer: 'Haydn',
    title: 'Surprise Symphony, II',
    youtubeId: 'VOLy6JxEDLw',
    week: 'Week 4-5-6',
    keyPoint: 'Soft twinkle and a Sudden LOUD chord! Written to wake up the audience.',
    youtubeStartTime: 35,
  },
  {
    composer: 'Mozart',
    title: 'The Vengeance of Hell Boils in My Heart',
    youtubeId: 'YuBeBjqKSGQ',
    week: 'Week 4-5-6',
    keyPoint: "'Queen of the Night' aria. Famously high notes.",
    youtubeStartTime: 62,
  },
  {
    composer: 'Dhamabutra',
    title: 'Pledge to HRH',
    youtubeId: 'QZIZbeppLto',
    week: 'Week 4-5-6',
    keyPoint: 'Contemporary Thai composer. Blends Thai & classical styles.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Rossini',
    title: 'William Tell Overture',
    youtubeId: 'xoBE69wdSkQ',
    week: 'Week 7-8-9',
    keyPoint: 'Galloping horses part is *The Lone Ranger* theme.',
    youtubeStartTime: 540,
  },
  {
    composer: 'Strauss II',
    title: 'Die Fledermaus Overture',
    youtubeId: '-IY4N_8BtHU',
    week: 'Week 7-8-9',
    keyPoint: 'Bubbly and energetic waltzes and polkas.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Offenbach',
    title: 'Can-Can',
    youtubeId: '4Diu2N8TGKA',
    week: 'Week 7-8-9',
    keyPoint: 'Famous high-kicking dance music.',
    youtubeStartTime: 75,
  },
  {
    composer: 'Saint-Saëns',
    title: 'The Swan',
    youtubeId: '3qrKjywjo7Q',
    week: 'Week 7-8-9',
    keyPoint: 'Graceful cello melody. Sounds like a gliding swan.',
    youtubeStartTime: 11,
  },
  {
    composer: 'Bizet',
    title: 'Habanera',
    youtubeId: 'K2snTkaD64U',
    week: 'Week 7-8-9',
    keyPoint: 'Sultry, dance-like aria from the opera *Carmen*.',
    youtubeStartTime: 58,
  },
  {
    composer: 'Tchaikovsky',
    title: 'Piano Concerto No.1, I',
    youtubeId: 'BWerj8FcprM',
    week: 'Week 7-8-9',
    keyPoint: 'Both Stiff + Clean sound. Powerful, famous piano chords at the start.',
    youtubeStartTime: 12,
  },
  {
    composer: 'Rimsky-Korsakov',
    title: 'Flight of the Bumble Bee',
    youtubeId: 'aYAJopwEYv8',
    week: 'Week 7-8-9',
    keyPoint: 'Extremely fast. Sounds like a buzzing bee.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Puccini',
    title: 'One Fine Day',
    youtubeId: '9uqPfArHlmU',
    week: 'Week 7-8-9',
    keyPoint: 'Emotional soprano aria from *Madama Butterfly*.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Fučík',
    title: 'Entrance of the Gladiators',
    youtubeId: '_B0CyOAO8y0',
    week: 'Week 7-8-9',
    keyPoint: 'The classic circus and clown music.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Rachmaninov',
    title: 'Vocalise',
    youtubeId: 'OhQaeDWlZ4A',
    week: 'Week 7-8-9',
    keyPoint: 'A song without words, sung on a single vowel.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Ives',
    title: 'Charlie Rutlage',
    youtubeId: 'kHMRAEAMuyY',
    week: 'Week 10-11-12',
    keyPoint: 'American cowboy story with chaotic folk singing and talking.',
    youtubeStartTime: 60,
  },
  {
    composer: 'Schoenberg',
    title: 'Pierrot lunaire',
    youtubeId: 'FkF5HY3QLTk',
    week: 'Week 10-11-12',
    keyPoint: 'Distorted melodies. Uses Sprechstimme (half-singing, half-speaking).',
    youtubeStartTime: 0,
  },
  {
    composer: 'Stravinsky',
    title: 'The Rite of Spring',
    youtubeId: 'EkwqPJZe8ms',
    week: 'Week 10-11-12',
    keyPoint: 'Caused riot/chaos at its premiere. Primal, harsh rhythms.',
    youtubeStartTime: 1994,
  },
  {
    composer: 'Prokofiev',
    title: 'Sonata No.7',
    youtubeId: 'bQbpzw0MHpc',
    week: 'Week 10-11-12',
    keyPoint: "'Stalingrad' sonata. Intense, motor-like final movement.",
    youtubeStartTime: 0,
  },
  {
    composer: 'Adams',
    title: 'China Gates',
    youtubeId: 'WwJs8M2SoS8',
    week: 'Week 10-11-12',
    keyPoint: 'Minimalist piano. Steady, flowing rhythm with slow changes.',
    youtubeStartTime: 0,
  },
  {
    composer: 'Dun',
    title: 'The Map',
    youtubeId: 'RAc1ecb-TqI',
    week: 'Week 10-11-12',
    keyPoint:
      'Blends Chinese & Western music. Using ordinary sounds as instruments (blowing leaf, stones, etc.)',
    youtubeStartTime: 80,
  },
];

// Deduplicate the list based on composer and title, keeping the first entry.
const uniqueKeys = new Set<string>();
export const MUSIC_LIST: MusicPiece[] = rawMusicData.filter(piece => {
  const key = `${piece.composer.toLowerCase()}|${piece.title.toLowerCase()}`;
  if (uniqueKeys.has(key)) {
    return false;
  }
  uniqueKeys.add(key);
  return true;
});

// Derive the list of weeks from the final, deduplicated MUSIC_LIST.
// This ensures the filter screen only shows weeks that have playable songs.
export const WEEKS = Array.from(new Set(MUSIC_LIST.map(p => p.week))).sort();
